### ISSUE TITLE
Running unmodified distaf fails with Python stack in geo_rep/test_geo_basic.py

### ISSUE THREAD

**Issue by nixpanic** [gluster/distaf#21]
When I run distaf from the main source directory, I get the following Python stack:
```
# ./main.py -c example.conf.yml 
Traceback (most recent call last):
  File "./main.py", line 117, in <module>
    main()
  File "./main.py", line 100, in main
    collect_tests()
  File "./main.py", line 36, in collect_tests
    __import__(iname.replace("/", "."))
  File "/opt/distaf/tests_d/geo_rep/test_geo_basic.py", line 4, in <module>
    @testcase("changelog-test-create")
  File "/opt/distaf/distaf/util.py", line 49, in decorator
    tc_config = get_testcase_config(func.__doc__)
  File "/opt/distaf/distaf/config_parser.py", line 33, in get_testcase_config
    config_dict = yaml.load(config_string)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/lib64/python2.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib64/python2.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib64/python2.7/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib64/python2.7/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'NoneType' object has no attribute 'read'
```
Removing the `tests_d/geo_rep` directory makes it possible to run the tests.

**Comment by msvbhat** [comment]
The geo_rep tests does not have any docstring (metadata yaml) specified. And in config parser i wasn't checking if the docstring is present or not. I put that check now and if there are no docstring in yaml, I apply the default to them.

**Comment by nixpanic** [comment]
Has this been merged? Maybe you can use https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by msvbhat** [comment]
Thanks @nixpanic, I did one other small change and that fixes the issue.
